[logging]
  level = "debug"

[backend.semtech_udp]
  udp_bind = "0.0.0.0:1701"
  fake_rx_time = false
  strict_ip = false
  timestamp_fix = "none"

[integration]
  marshaler = "json"

[integration.mqtt]
  event_topic_template = "eu868/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
  state_topic_template = "eu868/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
  command_topic_template = "eu868/gateway/{{ .GatewayID }}/command/#"
  [integration.mqtt.auth]
    generic.servers = ["tcp://mosquitto:1883"]

[integration.chirpstack]
  server = "http://chirpstack:8080"
  api_token = "XXXX"  # À CHANGER: token API ChirpStack
