name: "weewx"
services:
  weewx:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/data
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
    user: "0:0"
    environment:
      - TZ=Europe/Paris
      - PYTHONPATH=/data/lib/python

networks:
  lora-network:
    external: true
